branch-defaults:
  main:
    environment: imagefiltering-dev
    group_suffix: null
deploy:
  artifact: ./www/imagefiltering-archive.zip
global:
  application_name: imagefiltering
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
